[workspace]
members = ["renderer", "derive_renderer"]
resolver = "2"

[workspace.dependencies]
jinja-renderer = { version = "0.1", path = "renderer" }
derive-jinja-renderer = { version = "0.1", path = "derive_renderer" }
